version: '3.4'

services:
  test-backend:
    image: r0790759/project-backend
#     build:
#       context: .
#       dockerfile: /Dockerfile
    ports:
      - "80:80"
    depends_on:
          - db1

  db1:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"

    environment:
        SA_PASSWORD: "S3cur3P@ssW0rd!"
        ACCEPT_EULA: "Y"
